repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: check-docstring-first
  - id: debug-statements
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
    types_or: [c, c++, cuda]
    args: [-i, --sort-includes, ]
  # - id: cppcheck
  - id: cpplint
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.9.2
  hooks:
  - id: gersemi
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
  - id: hadolint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.284
  hooks:
  - id: ruff
    args: ['--fix', '--exit-non-zero-on-fix']
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    args: ['--line-length=79']
  - id: black-jupyter
    args: ['--line-length=79']
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
  - id: docformatter-venv
- repo: https://github.com/DanielNoord/pydocstringformatter
  rev: v0.7.3
  hooks:
  - id: pydocstringformatter
- repo: https://github.com/FlamingTempura/bibtex-tidy
  rev: v1.11.0
  hooks:
  - id: bibtex-tidy
    args: ['--curly', '--numeric', '--align=13', '--sort=-year,author',
           '--duplicates=key', '--no-escape', '--sort-fields', '--modify',
           '--remove-empty-fields', '--no-remove-dupe-fields', '--wrap=80']

exclude: '^(third_party/ORB-SLAM3/|viewer/)'
